const roles = [
    "Knight", "Mage", "Rogue", "Archer", "Paladin", "Blacksmith", "Healer", "Assassin", "Saint", "Tamer","Necromancer", "Unknown", "Death Knight", "Farmer", "Demon King", "Swordman", "Magic Swordman","Martial Artist", "Trader", "Archmage", "Slave", "Chef", "Rifleman", "Sapper", "Vampire","Berserker", "Bard", "Pirate", "Priest", "Alchemist", "Ranger", "Army Ranger", "Samurai", "Monk", "Vampire Lord", "Summoner", "Witch Hunter", "Dark Knight", "Scout", "Lancer", "Runesmith", "Champion", "Panzertruppe", "Military Pilot"
];
const races = [
    "Human", "Elf", "Dwarf", "Orc", "Beast", "Dark Elf", "Dragon", "Half Dragon", "Half Elf", "Demon", "Werewolf", "Succubus", "Divine Being", "Feline", "Frogman", "Lizardman", "Slime", "Jawir", "Sarkaz", "Liberi", "Sankta", "Deer", "Fishman", "Unknown", "Vampire", "Phoenix", "Giant", "Fairy", "Merfolk", "Gnome", "Troll", "Gargoyle", "Zombie", "Skeleton", "Harpy", "Minotaur", "Djinn", "Centaur", "Cyclops", "Satyr", "Dryad", "Spirit", "Naga", "Undead", "Goblin", "Elemental", "Chimera", "Griffin", "Treant", "Yeti", "Ogre"
];
const regions = [
    "LowRess Kingdom", "Liberia", "Great Forest", "Heavenhold", "Kingdom of Erusea", "Soviet Republics", "Drakenfell Mountains", "Evershade Isles", "Frostspire Tundra", "Ashenmoor Wastes", "Valoria", "Silverpeak Highlands", "Thornwood Vale", "Eldergrove", "Blackwater Marsh", "Suncrest Plains", "Ironcliff Bastion", "Whispering Sands", "Starlight Hollow", "Glimmerfall Cove", "Shadowfen Swamp", "Stormveil Coast", "Crimson Hollow", "Verdantwild", "Obsidian Flats", "Azurelake Shores", "Emberstone Citadel", "Duskmire Reach", "Wildthorn Expanse", "Goldenleaf Glade", "Ivoryspire City", "Osea Federation", "Yuktovania Republics"
];
const roleSkills = {
    "Knight": ["Sword Mastery", "Shield Mastery", "Mounted Combat", "War Cry", "Heavy Armor", "Tactical Strategy", "Battle Charge", "Shield Bash", "Combat Reflexes", "Defensive Stance", "Sword Block", "Battlefield Awareness", "Parry", "Shield Slam", "Armor Reinforcement", "Toughness", "Sword Precision", "Holy Vow", "Defender's Resolve", "Battle Endurance", "Total Immunity"],
    "Mage": ["Fire Magic", "Water Magic", "Earth Magic", "Wind Magic", "Lightning Magic", "Arcane Magic", "Teleportation", "Time Manipulation", "Illusion", "Energy Bolt", "Mana Control", "Dark Magic", "Summon Elementals", "Meteor Shower", "Magic Shield", "Mana Drain", "Arcane Blast", "Magic Ward", "Mana Burst", "Elemental Mastery", "Total Immunity"],
    "Rogue": ["Stealth", "Sneak Attack", "Lockpicking", "Pickpocketing", "Backstab", "Evasion", "Poison Crafting", "Agility Boost", "Silent Step", "Ambush", "Trap Detection", "Shadow Step", "Dagger Mastery", "Dual Wielding", "Smoke Bomb", "Shadow Meld", "Thievery", "Quick Escape", "Decoy", "Cloak of Shadows", "Total Immunity"],
    "Archer": ["Archery", "Tracking", "Trap Setting", "Camouflage", "Eagle Eye", "Quick Shot", "Bow Mastery", "Arrow Crafting", "Precision Shot", "Wind Guidance", "Critical Strike", "Multi Shot", "Long Range Mastery", "Animal Companion", "Piercing Arrow", "Explosive Arrow", "Double Shot", "Sniper Focus", "Hawk Eye", "Rapid Fire", "Total Immunity"],
    "Paladin": ["Holy Strike", "Divine Protection", "Healing", "Sword Mastery", "Shield of Faith", "Blessing of Light", "Aura of Courage", "Smite Evil", "Guardian's Shield", "Divine Resilience", "Holy Aura", "Purification", "Divine Judgement", "Divine Shield", "Light's Wrath", "Sacred Sword", "Healing Light", "Holy Hammer", "Divine Crusade", "Faith Barrier", "Total Immunity"],
    "Blacksmith": ["Blacksmithing", "Crafting", "Metal Manipulation", "Weapon Forging", "Armor Crafting", "Enchanting", "Repairing", "Mining", "Material Refinement", "Tool Crafting", "Metalworking", "Rune Engraving", "Weapon Enhancement", "Resource Management", "Hammer Strike", "Metal Shaping", "Smith's Endurance", "Ore Detection", "Forge Mastery", "Anvil Strike", "Total Immunity"],
    "Healer": ["Healing", "Potion Brewing", "Herbalism", "Light Magic", "First Aid", "Divine Touch", "Cure Disease", "Revitalize", "Holy Ward", "Life Restoration", "Group Healing", "Resurrection", "Mana Regeneration", "Protective Aura", "Restoration Surge", "Healing Circle", "Cleanse", "Renewal", "Sanctified Healing", "Restorative Light", "Total Immunity"],
    "Assassin": ["Stealth", "Poison Crafting", "Sneak Attack", "Dagger Mastery", "Critical Strike", "Dual Wielding", "Silent Step", "Shadow Meld", "Smoke Bomb", "Assassination", "Death Strike", "Vanish", "Shadow Clone", "Nerve Strike", "Ambush", "Silent Kill", "Toxin Expert", "Blinding Powder", "Heart Strike", "Deadly Precision", "Total Immunity"],
    "Saint": ["Blessing Magic", "Divine Protection", "Healing", "Charisma", "Inspiration", "Holy Flame", "Sanctuary", "Holy Light", "Miracle", "Divine Aura", "Sacred Shield", "Purify", "Light of Hope", "Holy Wrath", "Blessed Words", "Divine Intervention", "Blessing of Strength", "Holy Song", "Sacred Prayer", "Eternal Light", "Total Immunity"],
    "Tamer": ["Animal Training", "Beast Communication", "Taming Magic", "Summon Beast", "Beast Mastery", "Animal Bond", "Feral Rage", "Beast Riding", "Track Animals", "Command Beast", "Wild Frenzy", "Animal Empathy", "Beast Whisperer", "Tame Elemental", "Summon Spirit Beast", "Feral Protection", "Nature's Call", "Primal Roar", "Savage Charge", "Pack Leader", "Total Immunity"],
    "Necromancer": ["Necromancy", "Curse Magic", "Soul Magic", "Bone Magic", "Dark Ritual", "Raise Dead", "Undead Mastery", "Corpse Explosion", "Soul Drain", "Lich Transformation", "Plague Magic", "Life Drain", "Dark Pact", "Death's Embrace", "Graveborn", "Soul Reaver", "Spirit Shackles", "Shadow of Death", "Soul Harvest", "Deathly Aura", "Total Immunity"],
    "Unknown": ["Unknown Skill", "Mystery", "Hidden Talent", "Adaptability", "Survival Instinct", "Random Burst", "Eternal Enigma", "Shifting Powers", "Unpredictable Talent", "Foresight", "Chaos Manipulation", "Arcane Puzzle", "Reality Bending", "Anomalous Strength", "Unstable Magic", "Flicker Strike", "Quantum Leap", "Temporal Shift", "Mimic", "Darkness Within", "Total Immunity"],
    "Death Knight": ["Death Blade", "Soul Drain", "Plague Strike", "Undead Mastery", "Dark Armor", "Cursed Shield", "Death Charge", "Grim Command", "Necrotic Slash", "Unholy Aura", "Corpse Explosion", "Bone Shield", "Life Steal", "Dark Pact", "Vampiric Strike", "Reaper's Touch", "Soul Reaper", "Dark Command", "Death's Advance", "Doom Strike", "Total Immunity"],
    "Farmer": ["Harvesting", "Soil Knowledge", "Crop Mastery", "Animal Husbandry", "Seed Crafting", "Irrigation Mastery", "Plowing", "Plant Growth", "Land Fertility", "Livestock Care", "Crop Rotation", "Agricultural Trade", "Farming Tools", "Pest Control", "Farm Management", "Compost Creation", "Breeding Mastery", "Crop Forecasting", "Herbology", "Barn Construction", "Total Immunity"],
    "Demon King": ["Dark Command", "Infernal Flames", "Demon Summoning", "Absolute Domination", "Demonic Aura", "Soul Corruption", "Hellfire", "Dark Rebirth", "Demon Lord's Might", "Dark Pact", "Summon Demon Hordes", "Hellstorm", "Infernal Protection", "Shadow Flame", "Doom Prophecy", "Chaos Control", "Abyssal Magic", "Soul Reaver", "Eternal Torment", "Cursed Throne", "Total Immunity"],
    "Swordman": ["Sword Mastery", "Blade Dance", "Quick Strike", "Deflect", "Parry", "Sword Combo", "Sharp Focus", "Sword Spin", "Deadly Slash", "Sword Precision", "Sword Reflection", "Blade Guard", "Heavy Strike", "Sword Blitz", "Raging Slash", "Sword of Fury", "Rapid Slash", "Sword Counter", "Blade Crush", "Whirling Blade", "Total Immunity"],
    "Magic Swordman": ["Sword Mastery", "Elemental Blade", "Arcane Strike", "Mana Infusion", "Sword Dance", "Enchanted Weapon", "Magic Burst", "Quick Slash", "Spellblade", "Blade of Flames", "Ice Blade", "Lightning Edge", "Earth Cleave", "Wind Cutter", "Sword of Light", "Darkness Slash", "Sword Aura", "Mystic Edge", "Arcane Barrier", "Mana Shield", "Total Immunity"],
    "Martial Artist": ["Hand-to-Hand Combat", "Pressure Point Strike", "Fists of Fury", "Agility Boost", "Palm Strike", "Roundhouse Kick", "Counterattack", "Chi Focus", "Tiger Stance", "Dragon Kick", "Iron Fist", "Body Hardening", "Mental Focus", "Chi Channeling", "Flurry of Blows", "Disarm", "Sweeping Kick", "Nerve Strike", "Power Punch", "Energy Burst", "Total Immunity"],
    "Trader": ["Bartering", "Market Analysis", "Negotiation", "Wealth Accumulation", "Merchant's Eye", "Inventory Management", "Contract Drafting", "Supply Chain", "Risk Assessment", "Sales Mastery", "Trade Secrets", "Customer Rapport", "Trade Route Knowledge", "Investment Strategies", "Merchant's Luck", "Price Manipulation", "Logistics Expertise", "Market Expansion", "Haggling", "Wealth Control", "Total Immunity"],
    "Archmage": ["Ultimate Fireball", "Meteor Shower", "Elemental Mastery", "Arcane Surge", "Mystic Explosion", "Mana Mastery", "Teleportation", "Time Warp", "Mana Storm", "Reality Shatter", "Infinite Wisdom", "Arcane Barrage", "Planar Rift", "Arcane Manipulation", "Elemental Fury", "Cosmic Insight", "Eternal Flame", "Mana Explosion", "Spellsurge", "Mana Infusion", "Total Immunity"],
    "Slave": ["Endurance", "Survival Instinct", "Pain Tolerance", "Obedience", "Escape Artist", "Servitude Mastery", "Submission", "Silent Endurance", "Servant's Will", "Willpower", "Stealth Work", "Escape Plan", "Unseen Movement", "Rebellious Mind", "Survival Expert", "Hidden Talent", "Chained Strength", "Mental Resilience", "Resistance", "Hidden Strength", "Total Immunity"],
    "Chef": ["Cooking", "Ingredient Sourcing", "Flavor Mastery", "Knife Skills", "Heat Control", "Herb Knowledge", "Food Presentation", "Recipe Creation", "Gourmet Crafting", "Culinary Expertise", "Meal Preparation", "Food Preservation", "Baking Mastery", "Herb Infusion", "Ingredient Substitution", "Food Safety", "Multitasking", "Culinary Innovation", "Taste Testing", "Plating Expertise", "Total Immunity"],
    "Rifleman": ["Precise Aim", "Wind Estimation", "Critical Strike", "Lethality", "Mass Shooting", "Bayonet Fight", "Multishot", "Dead Eye", "Overload", "Suppresive Fire", "Close Air Support", "Guerrilla", "Artillery Bombardment", "Iron Clad", "Dual Welding", "Bullseye", "Total Focus", "Eyes In The Sky", "Infinite Mazagine", "Bulletproof", "Limit Break", "Two Birds One Stone", "APHE Shots", "Total Immunity", "Elemental Bullets"],
    "Sapper": ["Suppressive Fire", "Field Repair", "Bomb Defuse", "Sabotage", "Limit Break", "Iron Clad", "Marvelous Engineering", "Excavation", "Minesweeping", "Multitasking", "Confrontation", "No Retreat", "Demolition Expert", "Unconventional Warfare", "Eagle Eyes", "Damage Reduction", "Total Immunity", "Front Line Defense"],
    "Vampire": ["Total Immunity", "Blood Drain", "Bat Transformation", "Night Vision", "Immortal Presence", "Vampiric Aura", "Shadow Strike", "Dark Seduction", "Blood Pact", "Mist Form", "Blood Frenzy", "Summon Bats", "Night Stalker", "Immortal Regeneration", "Crimson Fury", "Charm of the Undead", "Blood Ritual", "Shadow Dash", "Nightwalker", "Hypnotic Gaze", "Vampire's Thrall"],
    "Berserker": ["Total Immunity", "Rage Unleashed", "Bloodlust", "Frenzied Strikes", "Battle Roar", "Relentless Assault", "Fearless Charge", "Savage Blow", "Battle Frenzy", "Bloodthirst", "Weapon Smash", "War Cry", "Unstoppable Force", "Rampage", "Critical Strike", "Battlefield Fury", "Rage Recovery", "Adrenaline Surge", "Destruction Wave", "Uncontrolled Rage", "Death Rage"],
    "Bard": ["Total Immunity", "Song of Valor", "Melodic Healing", "Inspiring Anthem", "Lute Mastery", "Song of Protection", "Charming Tune", "Magical Melody", "Harmonic Harmony", "Ballad of Bravery", "Rhythmic Defense", "Melody of Recovery", "Tune of Tranquility", "Battle Hymn", "Sonic Burst", "Hymn of Power", "Lullaby of Sleep", "Musical Shield", "Soundwave Shock", "Note of Clarity", "Inspiration Aura"],
    "Pirate": ["Total Immunity", "Swordplay", "Navigation", "Pistol Mastery", "Rum Drinking", "Sea Tactics", "Ship Management", "Plundering", "Treasure Hunting", "Cannon Operation", "Sea Combat", "Boarding Mastery", "Anchor Toss", "Sea Legs", "Whirlwind Slash", "Jolly Roger Spirit", "Oceanic Maneuvering", "Sail Mastery", "Rope Swing", "Pirate's Code", "Storm Riding"],
    "Priest": ["Total Immunity", "Holy Prayer", "Purify", "Healing Light", "Divine Intervention", "Blessing of Protection", "Resurrection", "Smite", "Holy Aura", "Faith Shield", "Prayer of Hope", "Restoration", "Spiritual Guidance", "Divine Judgment", "Miracle Healing", "Aura of Devotion", "Sermon of Light", "Benediction", "Martyrdom", "Prayer of Salvation", "Divine Grace"],
    "Alchemist": ["Total Immunity", "Potion Crafting", "Transmutation", "Herb Knowledge", "Elemental Infusion", "Elixir Mastery", "Alchemy Circle", "Catalyst Expertise", "Mana Elixirs", "Poison Brewing", "Stone Transmutation", "Antidote Creation", "Explosive Concoctions", "Potion of Speed", "Regeneration Brew", "Flame Essence", "Alchemy Enhancement", "Mana Restoration", "Resilience Brew", "Healing Elixirs", "Elemental Fusion"],
    "Ranger": ["Total Immunity", "Bow Mastery", "Tracking", "Stealth", "Hunting", "Nature Knowledge", "Animal Companion", "Cloak of Shadows", "Precision Shot", "Silent Kill", "Trap Setting", "Camouflage", "Survival Instinct", "Arrow Mastery", "Rapid Fire", "Animal Bond", "Foraging", "Evasion", "Swift Movements", "Lethal Arrow", "Wilderness Navigation"],
    "Army Ranger": ["Total Immunity", "Tracking", "Stealth", "Cloak of Shadows", "Precision Shot", "Camouflage", "Survival Instinct", "Rapid Fire", "Evasion", "Swift Movements", "Exceptional Navigation", "Medal of Honor Recipient"],
    "Samurai": ["Total Immunity", "Katana Mastery", "Bushido Code", "Quick Draw", "Parry", "Iaijutsu", "Sword Stance", "Focused Strike", "Spiritual Resolve", "Deflect Arrows", "Blade of Honor", "Perfect Focus", "Kiai", "Dual Katana", "Swift Blade", "Martial Spirit", "Battle Discipline", "Zen Meditation", "Blade Fury", "Warrior's Patience", "Sacred Oath"],
    "Monk": ["Total Immunity", "Chi Mastery", "Meditation", "Palm Strike", "Iron Fist", "Serene Mind", "Tiger Claw", "Pressure Point", "Swift Movement", "Chi Shield", "Inner Strength", "Spiritual Awareness", "Energy Channeling", "Keen Reflexes", "Healing Meditation", "Chi Burst", "Mystic Harmony", "Whirling Kick", "Fist of Fury", "Evasion", "Focused Breathing"],
    "Vampire Lord": ["Total Immunity", "Blood Drain", "Bat Transformation", "Night Vision", "Immortal Presence", "Vampiric Aura", "Shadow Strike", "Dark Seduction", "Blood Pact", "Mist Form", "Blood Frenzy", "Summon Bats", "Night Stalker", "Immortal Regeneration", "Crimson Fury", "Charm of the Undead", "Blood Ritual", "Shadow Dash", "Nightwalker", "Hypnotic Gaze", "Vampire's Thrall"],
    "Summoner": ["Total Immunity", "Summon Beast", "Arcane Summoning", "Summon Elemental", "Summon Golem", "Mana Channeling", "Familiar Mastery", "Summon Phoenix", "Spirit Bond", "Summon Doppelganger", "Ethereal Binding", "Summon Undead", "Mana Surge", "Summon Hydra", "Soul Link", "Summon Titan", "Elemental Convergence", "Arcane Familiar", "Conjure Guardian", "Planar Rift", "Summon Chimera"],
    "Witch Hunter": ["Total Immunity", "Dark Detection", "Purifying Flame", "Holy Shot", "Hunter's Mark", "Silver Bullets", "Dark Magic Nullification", "Curse Breaking", "Demonbane", "Vampire Slayer", "Purity of Will", "Mystic Ward", "Crossbow Mastery", "Exorcism", "Hunter's Reflexes", "Witch's Bane", "Trap Mastery", "Evil Scent", "Divine Smite", "Shadow Purge", "True Sight"],
    "Dark Knight": ["Total Immunity", "Shadow Strike", "Death Blade", "Dark Aura", "Nightmare Slash", "Soul Corruption", "Void Edge", "Unholy Strength", "Vampiric Touch", "Fell Cleave", "Shadow Barrier", "Blackened Blade", "Dark Shield", "Abyssal Wrath", "Soul Drain", "Grim Resolve", "Spectral Slash", "Voidwalker", "Dread Charge", "Cursed Armor", "Siphon Life"],
    "Scout": ["Total Immunity", "Keen Eye", "Ambush", "Tracking", "Silent Step", "Sniper Shot", "Camouflage", "Hawk's Vision", "Quick Shot", "Evasion", "Trap Mastery", "Trailblazer", "Agility Boost", "Escape Artist", "Deadly Aim", "Stealth Tactics", "Bow Mastery", "Terrain Mastery", "Survivalist", "Vantage Point", "Reconnaissance"],
    "Runesmith": ["Total Immunity", "Rune Crafting", "Weapon Inscription", "Armor Engraving", "Rune Empowerment", "Magic Infusion", "Rune of Fire", "Rune of Frost", "Rune of Protection", "Mystic Inscription", "Arcane Engravings", "Rune of Lightning", "Rune of Life", "Stone Rune", "Empowered Glyphs", "Rune Channeling", "Spirit Binding", "Rune of Destruction", "Mystic Warding", "Rune of Clarity", "Enchantment Mastery"],
    "Champion": ["Total Immunity", "Heroic Strike", "Battle Charge", "Defensive Posture", "War Cry", "Shield Bash", "Mighty Cleave", "Roar of the Champ", "Battle Endurance", "Overpower", "Critical Blow", "Tactical Defense", "Rallying Cry", "Victory Rush", "Stalwart Defense", "Unyielding Strength", "Shield Mastery", "Battlefield Domination", "Power Slam", "Warrior's Wrath"],
    "Panzertruppe": ["Total Immunity", "Mechanical Repairing", "Deadeye", "Tank Commander", "Precise Aim", "Overloader", "War Machine", "Panzer Ace", "King of the Battlefield", "The Future of Combat"],
    "Military Pilot": ["Air Superiority", "Bomber Hunter", "Fighter Hunter", "Night Fighter Expert", "Man and Machine Harmony", "Enhanced Awareness", "Top Gun Graduate", "Supermaneuverability", "Daredevil Flying", "Infantry's Best Friend", "Close Air Support Specialist", "Supercruising", "Expert Cargo Handler", "Quick Delivery", "Accurate Airdropping", "Sky Keeper", "SkyEye"]
};
const ranks = ["F", "E", "D", "C", "B", "A", "S", "SS", "SSS"];
const guilds = ["PSHT", "RHODES", "Silverthorn", "Dragonshade", "Shadowspire", "El Gasing", "Snowdwellers", "Yankees", "Killswitch", "Chronos"];
const titles = {
    "Knight": ["Champion of Light", "Guardian of the Realm", "Master of Arms", "Sword Guardian", "Defender of the Weak", "Anomaly", "Noob", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Mage": ["Master of Elements", "Arcane Scholar", "Stormcaller", "Elemental Weaver", "Mystic of the Arcane", "Anomaly", "Noob", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Rogue": ["Adept of Shadows", "Silent Blade", "Shadow Stalker", "Master Thief", "Cloaked Avenger", "Anomaly", "Noob"],
    "Archer": ["Eagle Eye", "Sharpshooter", "Bowmaster", "Hunter of the Wild", "Silent Marksman", "Anomaly", "Noob", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Paladin": ["Divine Protector", "Lightbringer", "Holy Crusader", "Guardian of the Faith", "Shield of Light", "Anomaly", "Noob", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Blacksmith": ["Master Blacksmith", "Forge Master", "Hammer of the Forge", "Steel Crafter", "Anvil Guardian", "Anomaly", "Noob"],
    "Healer": ["Grand Healer", "Life Restorer", "Saint of Light", "Divine Medic", "Reviver of Souls", "Anomaly", "Noob", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Assassin": ["Master Assassin", "Death's Whisper", "Silent Executioner", "Shadow's Edge", "Night Hunter", "Anomaly", "Noob"],
    "Saint": ["Blessed Savior", "Eternal Light", "Divine Speaker", "Holy Guardian", "Radiant Saint", "Anomaly", "Noob"],
    "Tamer": ["Beast Master", "Wild Whisperer", "Rider of Beasts", "Nature's Bond", "Animal Sovereign", "Anomaly", "Noob", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Necromancer": ["Necromancer King", "Master of the Dead", "Soul Weaver", "Lord of Shadows", "Gravecaller", "Anomaly", "Noob", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Unknown": ["Enigma", "Fate Twister", "Seeker of the Unknown", "Wielder of Chaos", "Shifter of Realms", "Anomaly", "Noob"],
    "Death Knight": ["Reaper of Souls", "Doombringer", "Knight of Death", "Grim Commander", "Bearer of Darkness", "Anomaly", "Noob", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Farmer": ["Harvest Lord", "Master of Fields", "Crop Sovereign", "Tiller of the Earth", "Lord of the Land", "Anomaly", "Noob"],
    "Demon King": ["Emperor of Flames", "Lord of Chaos", "Dark Overlord", "Hell's Ruler", "Master of Despair", "Anomaly", "Noob", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Swordman": ["Master Swordsman", "Blademaster", "Sword Sage", "Steel Tempest", "Blade Lord", "Anomaly", "Noob", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Magic Swordman": ["Arcane Blademaster", "Mystic Swordsman", "Elemental Bladesman", "Spellblade", "Mana Wielder", "Anomaly", "Noob", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Martial Artist": ["Master of Fists", "Chi Guardian", "Iron Fist", "Dragon Warrior", "Martial Master", "Anomaly", "Noob", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Trader": ["Master Merchant", "Goldfinger", "Wealth Accumulator", "Lord of Trade", "Market King", "Anomaly", "Noob"],
    "Archmage": ["Archmage Supreme", "Master of Magic", "Eternal Scholar", "Cosmic Magus", "Arcane Sovereign", "Anomaly", "Noob", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Slave": ["Survivor", "Endurer of Chains", "Liberated Soul", "Unseen Warrior", "Silent Strength", "Anomaly", "Noob"],
    "Chef": ["Ultimate Chef", "Gourmet King", "Master of Flavors", "Grand Cook", "Sovereign of Taste", "Anomaly", "Noob"],
    "Rifleman": ["Deadshot", "Precision Shooter", "Pistol Specialist", "Rifle Expert", "Marine for Life", "Black Baron", "Anomaly", "Noob", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Sapper": ["Bomb Defuser", "Field Repair Specialist", "Handyman", "Master of Engineering", "Nutcracker", "Anomaly", "Noob", "Codebreaker", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Berserker": ["Rage of the Battlefield", "Warrior of Fury", "Bloodthirsty Destroyer", "Wielder of Wrath", "Fury Unleashed", "Madman of Battle", "Bringer of Carnage", "The Frenzied", "Wrathbringer", "Destroyer of Foes", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Bard": ["Songweaver", "Master of Melody", "Minstrel of Legends", "Keeper of Tales", "Harmonious Singer", "Traveler's Song", "Poet of Ages", "Muse of the Realm", "Melody Maker", "Voice of the Ages", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Pirate": ["Captain of the Seas", "Sea Rover", "Lord of the Ocean", "Buccaneer King", "Ruler of the Waves", "Master of the High Seas", "Ocean Raider", "Corsair Champion", "Scourge of the Waters", "Seafaring Marauder"],
    "Priest": ["Blessed Cleric", "Voice of the Divine", "Keeper of Faith", "Holy Shepherd", "Bearer of Grace", "Soul Keeper", "Divine Intercessor", "Servant of the Light", "Harbinger of the Sacred", "Guardian of the Faithful"],
    "Alchemist": ["Master of Transmutation", "Potion Master", "Crafter of Elixirs", "Herbalist of the Realms", "Arcane Chemist", "Wielder of Elements", "Mixer of Potions", "Catalyst of Change", "Enchanter of Potions", "Alchemical Sage"],
    "Ranger": ["Warden of the Wilds", "Guardian of Nature", "Tracker of Beasts", "Forest Wanderer", "Nature's Protector", "Hunter of the Wild", "Beast Seeker", "Woodsman of the Realm", "Pathfinder", "Wilds Keeper", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Army Ranger": ["Infilltration", "Slient Hunter", "Survival Expert", "Grenade Specialist", "Jungle Warfare Expert", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Samurai": ["Warrior of Honor", "Master of the Katana", "Bushido Blade", "Sword of Honor", "Lord of the Katana", "Disciple of Bushido", "Master of the Sword", "Ronin of Valor", "Keeper of the Code", "Blade of Honor", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Monk": ["Disciple of Peace", "Master of Tranquility", "Fist of the Ancients", "Silent Guardian", "Wanderer of Virtue", "Keeper of Balance", "Mystic Warrior", "Guardian of Serenity", "Devout of the Spirit", "Master of Harmony"],
    "Vampire Lord": ["Dark Blood King", "Lord of Night", "Sovereign of Shadows", "Ruler of the Undead", "Master of Vampires", "Night Stalker", "Bloodthirsty Monarch", "Shadow Emperor", "Darkblood Ruler", "Wraith of the Night", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Summoner": ["Caller of Beasts", "Master of Summons", "Wielder of Creatures", "Invoker of Allies", "Summoner of Realms", "Creature Caller", "Beast Conjuror", "Spirit Summoner", "Master of Conjurations", "Herald of Creatures", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Witch Hunter": ["Hunter of Witches", "Bane of Sorcery", "Protector of Innocents", "Cleansing Flame", "Purger of Darkness", "Slayer of Magic", "Witchbane", "Champion of Light", "Shadow Purger", "Light's Retribution", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Dark Knight": ["Knight of Shadows", "Bearer of Darkness", "Ruler of Night", "Wielder of the Void", "Shadowbringer", "Champion of Despair", "Harbinger of Night", "Darkblade", "Knight of the Abyss", "Warlord of the Void", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Scout": ["Pathfinder of the Wild", "Master Tracker", "Seeker of Secrets", "Ranger of the Unknown", "Warden of the Wilds", "Lightfoot", "Silent Watcher", "Tracker of Beasts", "Explorer of Realms", "Wilderness Wanderer", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Runesmith": ["Master of Runes", "Carver of Magic", "Wielder of Ancient Symbols", "Runewright", "Smith of Power", "Crafter of Enchantment", "Runescribe", "Bearer of Magical Symbols", "Runeforge Master", "Lord of the Runes"],
    "Champion": ["Hero of the People", "Guardian of the Realm", "Sword of Victory", "Master of the Arena", "Warlord of Glory", "Victor of the Colosseum", "Lord of Triumph", "Conqueror of Realms", "Battle Champion", "Champion of Legends", "Great War Participant - Winning Side"],
    "Panzertruppe": ["Panzer Ace", "Anti-Aircraft Warfare Specialist", "Tank Warfare Specialist", "Kommandant", "Destroyer of Battlefield", "Russian Bias", "Infantry Support Specialist", "Camouflage Expert", "Urban Warfare Specialist", "Airborne Cleaner", "Black Baron", "Fresh off the Academy", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
    "Military Pilot": ["The Three Strikes", "Mister X", "The Demon Lord of the Round Table", "The Red Baron", "The Grim Reaper", "The Black Devil", "Flying Knight of the Northland", "The Mad Major", "Bad Omen", "Black Baron", "Mr. Murderer", "Infantry's Friend", "Die Zerstörer", "Fresh off the Academy", "The Silver Fox", "Cargo Hauler", "No Where to Hide", "Radar Operator Specialist", "Cargo Plane Expert", "Cargo Tender", "Long Caster", "Great War Participant - Winning Side", "Great War Participant - Losing Side"],
};
const roleWeapon = {
    "Knight": ["Heavy Sword", "Short Sword", "Sword and Shield", "Spear", "Club", "Bat"],
    "Mage": ["Staff of Water", "Staff of Earth", "Staff of Fire", "Staff of Darkness", "Metal Staff", "Magic Book"],
    "Rogue": ["Daggers", "Short Sword", "Switchblade", "Club", "Cleaver", "Silenced Pistol"],
    "Archer": ["Longbow", "Quick-fire Bow", "Elemental Bow", "Crossbow"],
    "Paladin": ["Heavy Sword", "Short Sword", "Sword and Shield"],
    "Blacksmith": ["Hammer", "Anvil", "Pickaxe", "Shovel", "Axe"],
    "Healer": ["Staff of Cleanse", "Staff of Healing", "Staff of Regeneration", "Book of Healing"],
    "Assassin": ["Katana", "Wakizashi", "Shuriken", "Daggers", "Sickle"],
    "Saint": ["Unknown"],
    "Tamer": ["Bear", "Crocodile", "Dinosaur", "Elephant", "Tiger", "Leopard"],
    "Necromancer": ["Staff of Darkness", "Staff of Skull", "Femur", "Bone Staff", "Book of the Undead"],
    "Unknown": ["Unknown"],
    "Death Knight": ["Reaper", "Undead Heavy Sword", "Short Sword of Death", "Sword and Shield", "Spear", "Club", "Bat"],
    "Farmer": ["Sickles", "Pitchforks", "Sticks", "Stone", "Bat"],
    "Demon King": ["Unknown"],
    "Swordman": ["Heavy Sword", "Short Sword", "Daggers", "Katana", "Wakizashi", "Cleaver"],
    "Magic Swordman": ["Magic-induced Heavy Sword", "Magic-induced Short Sword", "Magic-induced Daggers", "Magic-induced Katana", "Magic-induced Wakizashi", "Magic-induced Cleaver"],
    "Martial Artist" :["Barehand", "Nunchucks", "Fighting Gloves"],
    "Trader": ["None"],
    "Archmage": ["Staff of Water", "Staff of Earth", "Staff of Fire", "Staff of Darkness", "Metal Staff", "Magic Book", "Staff of Darkness", "Staff of Skull", "Femur", "Bone Staff", "Book of the Undead"],
    "Slave": ["None"],
    "Chef": ["Cleaver", "Axe", "Spatula", "Saucepan", "Wok", "Pot", "Kettle", "Rolling Pin", "Knife"],
    "Rifleman": ["Pistol", "Revolver", "Submachine Gun", "Shotgun", "Assault Rifle", "Light Machine Gun", "Heavy Machine Gun", "Sniper Rifle"],
    "Sapper": ["C4 Pack", "Grenade", "GP Machine Gun", "RPG", "Mortar Launcher", "Grenade Launcher", "Panzerfaust", "Pistol", "Revolver", "Flamethrower"],
    "Vampire": ["Fangs", "Claws"],
    "Berserker": ["Two-Handed Sword", "Battle Axe", "Heavy Sword", "Spear and Shield", "Zweihander", "Mjolnir Hammer"],
    "Bard": ["None"],
    "Pirate": ["Flintlock Pistol", "Quickslash Sword", "Cannon", "Hook"],
    "Priest": ["None"],
    "Alchemist": ["None"],
    "Ranger": ["Longbow", "Quick-fire Bow", "Elemental Bow", "Crossbow", "Daggers", "Short Sword"],
    "Army Ranger": ["Submachine Gun", "Revolver", "Pistol", "Daggers", "Semi-Auto Rifle", "Bolt-Action Rifle"],
    "Samurai": ["Bajō-zutsu", "Bo-hiya", "Daishō", "Tanegashima", "Wakizashi", "Shuriken"],
    "Monk": ["Fists"],
    "Vampire Lord": ["Fangs", "Claws"],
    "Summoner": ["Iron Golem", "Diamond Golem", "Warden", "Snow Warden", "Ender Dragon", "Ghast", "Lava Warden"],
    "Witch Hunter": ["Stake", "Revolver", "Axe", "Lighter", "Torch", "Pitchfork", "Counterspell"],
    "Dark Knight": ["Dark Heavy Sword", "Dark Short Sword", "Spear", "Club", "Bat", "Quickslash Sword of Darkness"],
    "Scout": ["Rifle", "Submachine Gun", "Pistol", "Dagger", "Short Sword", "Smoke Grenade", "Flare Gun"],
    "Runesmith": ["Book of Rune"],
    "Panzertruppe": ["Light Tank", "Tankette", "Self-Propelled Gun", "Medium Tank", "Self-Propelled Anti-Aircraft Vehicle", "Heavy Tank", "Super Heavy Tank", "Main Battle Tank", "Infantry Fighting Vehicle/Armor Support Vehicle", "Armored Personnel Carrier"],
    "Military Pilot": ["Fighter", "Heavy Fighter", "Multirole Fighter/Fighter-Bomber", "Light Bomber", "Medium Bomber", "Heavy Bomber", "Reconnaissance Aircraft", "Helicopter", "Transport Plane/Refuelling Tanker", "Airborne Warning and Control System"]
};
const tankVariants = {
    "PSHT": {
        "Light Tank": ["T-18", "T-26", "T-50", "T-60", "T-70", "PT-76", "BT-5", "BT-7", "RBT-5", "PT-76-57", "2S25", "2S25M", "2S38"], 
        "Tankette": ["T-27"], 
        "Self-Propelled Gun": ["SU-76", "SU-85", "SU-100", "SU-122", "SU-152", "ISU-122", "ISU-152", "SU-57", "ASU-57"], 
        "Medium Tank": ["T-28", "T-34", "T-34-85", "T-44", "T-54/55"],
        "Self-Propelled Anti-Aircraft Vehicle": ["ZSU-37", "ZSU-37-2", "ZSU-57-2", "ZSU-23-4", "Osa-M", "Pantsir-S1", "Strela-10", "2S6"],
        "Heavy Tank": ["KV-1", "KV-2", "IS-85/IS-1", "IS-2", "IS-3", "IS-4", "T-10"],
        "Super Heavy Tank": ["T-35", "SMK"],
        "Main Battle Tank": ["T-62", "T-64", "T-72", "T-80", "T-90", "T-14 Armata"],
        "Infantry Fighting Vehicle/Armor Support Vehicle": ["BMP-1", "BMP-2", "BMP-3", "BMP-2M", "BMPT Terminator"],
        "Armored Personnel Carrier": ["BTR-80A", "BTR-82AT", "BMD-4", "BMD-4M", "BMD-4M2"]
    },
    "RHODES": {
        "Light Tank": ["Ka-Mi", "Ha-Go", "Ke-Ni", "Type 16"],
        "Tankette": ["Type 94", "Type 97 Te-Ke"],
        "Self-Propelled Gun": ["Ro-Go", "Ho-Ro",, "Chi-Ha LG", "Ho-Ni I", "Ho-Ni III", "Na-To", "Type 99", "Ho-Ri", "Type 60 SPRG", "Type 75 SPH"],
        "Medium Tank": ["Ka-Chi", "Chi-He", "Ho-I", "Chi-Ha", "Chi-Ha Kai", "Chi-Nu", "Chi-To", "Chi-Ri"],
        "Self-Propelled Anti-Aircraft Vehicle": ["Ta-Se", "So-Ki", "Type 87", "Type 93"],
        "Heavy Tank": ["Ro-Go", "Pz.Kpfw VI 'Tiger I'"],
        "Super Heavy Tank": ["O-I"],
        "Main Battle Tank": ["Type 61", "Type 74", "Type 90", "Type 10"],
        "Infantry Fighting Vehicle/Armor Support Vehicle": ["Type 24 ICV", "Type 87 RCV", "Type 89"],
        "Armored Personnel Carrier": ["Type 63", "Type 70"]
    },
    "Silverthorn": {
        "Light Tank": ["AMC.34", "FCM.36", "H.35", "H.39", "R.35", "AMX-13", "E.B.R.", "AMX-10RC"],
        "Tankette": ["AMD.35", "AML-90", "EBRC Jaguar"],
        "Self-Propelled Gun": ["AMR.35 ZT3", "Lorraine 37L", "SAu 40", "AuF1"],
        "Medium Tank": ["D2", "S.35"],
        "Self-Propelled Anti-Aircraft Vehicle": ["AMX-13 DCA 40", "TPK 6.41", "CCKW 353 AA", "AMX-30 S DCA", "Roland 1", "SANTAL"],
        "Heavy Tank": ["AMX-50 Surblindé", "AMX-50 Surbaissé", "Char B1", "ARL-44"],
        "Super Heavy Tank": ["Char 2C bis"],
        "Main Battle Tank": ["AMX-30", "Leopard 2", "Leclerc MBT"],
        "Infantry Fighting Vehicle/Armor Support Vehicle": ["VBCI"],
        "Armored Personnel Carrier": ["VAB"]
    },
    "Dragonshade": {
        "Light Tank": ["A13 Cruiser", "A15 Crusader", "Scimitar", "VFM5"],
        "Tankette": ["Tetrach I", "Daimler Mk II", "Harry Hopkins I", "Fox"],
        "Self-Propelled Gun": ["Alecto Mk.I", "Archer", "Tortoise"],
        "Medium Tank": ["Cromwell I", "Cromwell V", "Valentine I", "Valentine IX", "Valentine XI", "A30 Challenger", "A30 SP Avenger", "Comet I", "Centurion"],
        "Self-Propelled Anti-Aircraft Vehicle": ["Light AA Mk I", "Crusader AA Mk I", "Crusader AA Mk II", "Tracked Rapier", "Stormer AD"],
        "Heavy Tank": ["Matilda III", "Churchill", "Conqueror", "Caernarvon"],
        "Super Heavy Tank": ["Independent", "TOG II"],
        "Main Battle Tank": ["Vickers Mk.1", "Chieftain", "Vickers Mk.3", "Challenger 2"],
        "Infantry Fighting Vehicle/Armor Support Vehicle": ["FV510 Warrior", "Ajax"],
        "Armored Personnel Carrier": ["FV432", "Ocelot", "FV103 Spartan", "Humber Pig", "Saxon"]
    },
    "Shadowspire": {
        "Light Tank": ["L6/40", "M11/39", "AUBL/74", "C13 T90", "Centauro I 105"],
        "Tankette": ["AB 41", "L3/33 CC"],
        "Self-Propelled Gun": ["47/32 L40", "Breda 501", "90/53 M41M"],
        "Medium Tank": ["M13/40"],
        "Self-Propelled Anti-Aircraft Vehicle": ["CM52", "SIDAM 25"],
        "Heavy Tank": ["Pz.Kpfw VI 'Tiger I'"],
        "Super Heavy Tank": [null],
        "Main Battle Tank": ["OF-40", "Ariete"],
        "Infantry Fighting Vehicle/Armor Support Vehicle": ["VBC (PT2)", "VCC-80/60", "Dardo", "Freccia", "VCC-80/30"],
        "Armored Personnel Carrier": ["FIAT 6614"]
    },
    "El Gasing": {
        "Light Tank": ["Pz.Kpfw 35(t)", "Pz.Kpfw 38(t)", "Pz.Kpfw II", "Sd.Kfz.234/2", "DF105", "PUMA"],
        "Tankette": ["Sd.Kfz. 140/1", "Sd.Kfz.221 (s.Pz.B.41)", "Luchs A2", "Sd.Kfz.222"],
        "Self-Propelled Gun": ["Panzerjäger I", "StuG III", "Sd.Kfz.234/3", "Sd.Kfz.251/10", "Sturmpanzer II 'Bison'", "Marder III", "Dicker Max", "Sturer Emil", "StuH 42", "Jagdpanzer 38(t) 'Hetzer'", "Jagdpanzer IV", "Nashorn", "Panzer IV/70", "Sd.Kfz.234/4", "8,8 cm Flak 37 Sfl.", "Sturmpanzer IV Brummbär", "VFW", "JPz 4-5", "Jagdpanther G1", "Jagdtiger", "Ferdinand", "PzH 2000"],
        "Medium Tank": ["Pz.Kpfw III Ausf. E", "Pz.Kpfw III Ausf. N", "Pz.Kpfw IV Ausf. F1", "Pz.Kpfw IV Ausf. H", "Panther"],
        "Self-Propelled Anti-Aircraft Vehicle": ["Flakpanzer 38", "Flakpanzer I", "Sd.Kfz.222", "Sd.Kfz. 6/2", "Sd.Kfz.251/21", "Flakpanzer IV 'Ostwind'", "Flakpanzer IV 'Wirbelwind'", "Wiesel 1A4", "Gepard", "Ozelot", "FlaRakPz 1", "FlaRakRad"],
        "Heavy Tank": ["Pz.Kpfw VI 'Tiger I'", "Pz,Kpfw Tiger Ausf. B 'Tiger II'"],
        "Super Heavy Tank": ["E-100", "Maus"],
        "Main Battle Tank": ["Leopard 1", "Leopard 2"],
        "Infantry Fighting Vehicle/Armor Support Vehicle": ["SPz 12-3 LGS", "Marder", "Sd.Kfz.251/9", "Wiesel 1A2"],
        "Armored Personnel Carrier": ["Boxer MGS", "Raketenautomat"]
    },
    "Snowdwellers": {
        "Light Tank": ["Strv m/31", "Strv m/38", "Strv m/40L", "Strv 74", "CV 90105 TML", ],
        "Tankette": ["Pbil m/40"],
        "Self-Propelled Gun": ["Ikv 72", "Sav m/43", "Bkan 1C"],
        "Medium Tank": ["Ikv 73", "Strv m/42"],
        "Self-Propelled Anti-Aircraft Vehicle": ["VEAK 40", "ASRAD-R", "Lvkv 9040C", "EldE 98"],
        "Heavy Tank": ["Pz.Kpfw Tiger Ausf. B 'Tiger II'(P)"],
        "Super Heavy Tank": [null],
        "Main Battle Tank": ["Strv 101", "Strv 103", "Strv 81", "Strv 122"],
        "Infantry Fighting Vehicle/Armor Support Vehicle": ["Pbv 501", "Ikv 91", "Strf 9040B", "CV 90 Mk.IV", "Pbv 301"],
        "Armored Personnel Carrier": ["Pbv 302"]
    },
    "Yankees": {
        "Light Tank": ["M22 Locust", "M2A4", "M3 Stuart", "M24 Chaffee", "M5 Stuart", "M41 Walker Bulldog", "M551 Sheridan", "Stingray", "M1128"],
        "Tankette": ["M2A2", "M8 LAC", "T18E2"],
        "Self-Propelled Gun": ["M18 GMC 'Hellcat'", "M3 GMC", "M8 HMC", "M10 GMC 'Wolverine'", "M36 GMC", "M44", "M55", "M109A1 Paladin", "M50", "M56 Scorpion"],
        "Medium Tank": ["M3 Lee", "M4 Sherman", "M26 Pershing", "M47 Patton II", "M48A1 Patton"],
        "Self-Propelled Anti-Aircraft Vehicle": ["M13 MGMC", "M15 CGMC", "M19A1 MGMC", "M42 Duster", "M163 VADS", "M247 Sergeant York DIVAD", "Imp.Chaparral", "LAV-AD"],
        "Heavy Tank": ["T26E5", "M103"],
        "Super Heavy Tank": ["T95"],
        "Main Battle Tank": ["M60", "M1 Abrams"],
        "Infantry Fighting Vehicle/Armor Support Vehicle": ["LVT(A)", "M3 Bradley"],
        "Armored Personnel Carrier": ["M3 Bradley"]
    },
    "Killswitch": {
        "Light Tank": ["Bardelas/60mm HVMS"],
        "Tankette": [null],
        "Self-Propelled Gun": ["Rochev"],
        "Medium Tank": ["Tiran 4", "Sabra Mk.I"],
        "Self-Propelled Anti-Aircraft Vehicle": ["Hovet", "TCM-20", "SPYDER", "Machbet"],
        "Heavy Tank": [null],
        "Super Heavy Tank": [null],
        "Main Battle Tank": ["Gal Batash", "Tiran 6", "Merkava"],
        "Infantry Fighting Vehicle/Armor Support Vehicle": ["Namer Tsrikhon"],
        "Armored Personnel Carrier": ["Namer 30", "Namer Tsrikhon"]
    },
    "Chronos": {
        "Light Tank": ["Type 62", "Type 63"],
        "Tankette": ["PTL02"],
        "Self-Propelled Gun": ["PLZ83", "PLZ05", "PTZ89 'Eastern Ferdinand'"],
        "Medium Tank": ["Type 59", "Type 69"],
        "Self-Propelled Anti-Aircraft Vehicle": ["ZSD63/PG87", "WZ305", "PGZ04A", "PGZ09", "HQ11", "HQ17", 'CS/SA5'],
        "Heavy Tank": [null],
        "Super Heavy Tank": [null],
        "Main Battle Tank": ["ZTZ88", "ZTZ96", "VT4", "ZTZ99"],
        "Infantry Fighting Vehicle/Armor Support Vehicle": ["ZBD86", "CM34", "QN506", "ZBD04A", "ZLT11"],
        "Armored Personnel Carrier": ["WZ551"]
    }
};
const aircraftVariants = {
    "PSHT": {
        "Fighter": ["I-153 M-62", "I-15", "I-16", "MiG-3", "La-5", "LaGG-3", "Yak-1", "Yak-7", "Yak-9", "La-7", "Yak-3", "La-9", "MiG-15", "Su-9", "MiG-17", "MiG-21", "MiG-23", "MiG-29", "Su-7"],
        "Heavy Fighter": ["MiG-25", "MiG-31", "Su-27", "Su-33", "Pe-3", "Yak-2 KABB"],
        "Multirole Fighter/Fighter-Bomber": ["Su-30", "Yak-38", "Su-17/Su-22", "Su-34", "Su-35", "Su-57"],
        "Light Bomber/CAS": ["BB-1", "Il-2 Shturmovik", "Su-2", "Su-6", "Su-7", "Su-25", "Yak-4"],
        "Medium Bomber": ["Su-24", "Ar-2", "SB 2M", "DB-3", "IL-4", "Yer-2", "Tu-2", "IL-28", "Tu-14", "Tu-16"],
        "Heavy Bomber": ["TB-3M", "Pe-8", "Be-6", "Yak-28", "Tu-95", "Tu-160", "Tu-22"],
        "Reconnaissance Aircraft": ["KOR-1", "Po-2", "Yak-4", "MiG-25"],
        "Helicopter": ["Mi-24", "Mi-4", "Mi-8", "Ka-29", "Ka-50", "Ka-52", "Mi-28", "Mi-35"],
        "Transport Plane/Refuelling Tanker": ["An-8", "An-12", "An-22", "An-26", "An-32", "Il-76", "An-124 'Ruslan'", "An-225 'Mriya'", "Il-78"],
        "Airborne Warning and Control System": ["A-50", "Tu-126", "Ka-31"]
    },
    "RHODES": {
        "Fighter": ["A5M", "Ki-27", "Ki-10", "Ki-43", "A6M 'Zero'", "Ki-44", "Ki-61 'Hien'", "N1K", "J2M", "Ki-100", "A7M2 'Reppu'", "J6K", "J7W", "Ki-84 'Hayate'", "Ki-87", "N1K1-J", "N1K2-J", "Ki-94", "Kikka", "T-2", "F1M"],
        "Heavy Fighter": ["Ki-45", "J1N", "Ki-102", "J5N", "Ki-83", "Ki-45", ],
        "Multirole Fighter/Fighter-Bomber": ["F-1", "F-15J", "F-2A Kai", "F-2A Super Kai"],
        "Light Bomber/CAS": ["Ki-102", "E13A1", "B5N", "E7K", "E8N", "F1M", "Ki-32", "B6N 'Tenzan'", "D4Y 'Suisei'", "Ki-48", "B7A", "D3A"],
        "Medium Bomber": ["Ki-21", "G3M", "G4M", "Ki-49", "P1Y1"],
        "Heavy Bomber": ["H6K", "H8K", "G5N 'Shinzan'", "Ki-67", "G8N 'Renzan'"],
        "Reconnaissance Aircraft": ["E7K", "E8N", "F1M", "Ki-46"],
        "Helicopter": ["AH-1S", "AH-64DJP", "UH-1B"],
        "Transport Plane/Refuelling Tanker": ["Ki-56", "Ki-57", "Ki-34", "Nakajima L2D", "Kawasaki C-1", "Kawasaki C-2", "KC-767"],
        "Airborne Warning and Control System": ["Boeing E-767"]
    },
    "Silverthorn": {
        "Fighter": ["D.371", "D.500", "H-75A", "M.B.151", "D.520", "M.S.410", "V.G.33", "NC.900", "M.D.450B Ouragan", "S.O.4050 Vautour", "Mirage IIIC"],
        "Heavy Fighter": ["Potez 630"],
        "Multirole Fighter/Fighter-Bomber": ["Super Mystere B2", "Mirage 2000", "Mirage 4000", "Rafale", "Jaguar"],
        "Light Bomber/CAS": ["Br.693AB2", "Alpha Jet E", "Potez 633", "V-156-F", "LeO 451", "S.O.4050 Vautour II", ],
        "Medium Bomber": ["F.222.2", "M.B.175", "S.O.4050 Vautour IIB"],
        "Heavy Bomber": ["M.B.162"],
        "Reconnaissance Aircraft": ["GL.832HY", "Loire 130"],
        "Helicopter": ["H-34", "SA 313 'Alouette II'", "SA.341 'Gazelle'", "EC-665 'Tiger'"],
        "Transport Plane/Refuelling Tanker": ["ATR 72", "A400M", "Bréguet 941", "C-160", "A330 MRTT 'Phénix'"],
        "Airborne Warning and Control System": ["Boeing E-3 Sentry"],
    },
    "Dragonshade": {
        "Fighter": ["Fury", "Gladiator", "Sea Gladiator", "Nimrod", "Boomerang", "Martlet", "Hurricane", "Sea Hurricane", "Spitfire", "Hellcat", "Typhoon", "Thunderbolt", "Seafire", "Sea Fury", "Tempest", "Meteor F", "Sea Venom", "Swift F", "Hunter F", "Javelin F.(A.W.)", "Lightning F"],
        "Heavy Fighter": ["Whirlwind", "Hornet", "Phantom FGR.2", "Phantom FG.1", "Beaufighter", ],
        "Multirole Fighter/Fighter-Bomber": ["Attacker FB", "Vampire F.B", "Hunter FGA", "Typhoon FGR.4", "F-35C", "Sea Harrier II", "Tornado F", "Brigand B 1", "Mosquito", "Harrier GR", "Hawk 200", "Jaguar", "Tornado"],
        "Light Bomber/CAS": ["Swordfish", "Chesapeake", "Avenger", "Buccaneer S", "Firefly F"],
        "Medium Bomber": ["Beaufort", "Blenheim", "Hampden", "Catalina", "Boston", "Hudson", "Havoc", "Wellington", "Wyvern S"],
        "Heavy Bomber": ["Halifax", "Stirling", "Lancaster", "Lincoln", "Shackleton", "Canberra", "Vulcan"],
        "Reconnaissance Aircraft": ["Walrus", "Osprey", "Hudson", "Sunderland"],
        "Helicopter": ["Scout", "Wasp", "Lynx", "Chinook", "Jupiter HC.2"],
        "Transport Plane/Refuelling Tanker": ["Lodestar", "Globemaster III", "Harrow", "Atlas", "Falcon 900", "Voyager"],
        "Airborne Warning and Control System": ["Boeing E-7 Wedgetail"]
    },
    "Shadowspire": {
        "Fighter": ["CR.32", "CR.42", "G.50", "Re.2000", "C. 202", "C. 200", "Re.2001", "G.55", "Re.2005", "C. 205", "CL-13", "G.91"],
        "Heavy Fighter": ["F.C.20", "SM.91"],
        "Multirole Fighter/Fighter-Bomber": ["F-2000A", "Tornado"],
        "Light Bomber/CAS": ["Ba.65 (K.14) L", "MB-326K", "A-11 Ghibli"],
        "Medium Bomber": ["F.C.20", "Breda 88", "B.R.20DR", "S.M.79", "S.81", "Z.1007 bis serie 5", ],
        "Heavy Bomber": ["P.108A Artgliere"],
        "Reconnaissance Aircraft": ["Ro.43", "Ro.44", "G.91"],
        "Helicopter": ["AB 205", "A.109", "A129"],
        "Transport Plane/Refuelling Tanker": ["Z.511", "Z.1011", "KC-767", "A400M"],
        "Airborne Warning and Control System": ["EH-101A AEW"]
    },
    "El Gasing": {
        "Fighter": ["Bf 109", "He 51", "Fw 190A 'Würger'", "Fw 190D 'Würger'", "Ta 152", "Me 163", "Me 262"],
        "Heavy Fighter": ["Me 410 'Hornisse'", "Ta 154", "Bf 110", "Do 335 'Pfeil'"],
        "Multirole Fighter/Fighter-Bomber": ["Do 17", "Ju 88", "Ju 388", "Fw 190F", "Tornado", "EF2000", "Do 217",],
        "Light Bomber/CAS": ["Ju 87 'Stuka'", "Alpha Jet A", "Hs 123"],
        "Medium Bomber": ["Do 17 'Fliegender Bleistift'", "He 111", "Ju 188", "Ar 234"],
        "Heavy Bomber": ["Fw 200", "He 177", "Me 264"],
        "Reconnaissance Aircraft": ["Ar 196", "BV 138", "Ar 234"],
        "Helicopter": ["BO 105", "EC-665"],
        "Transport Plane/Refuelling Tanker": ["Ju 52", "Me 323", "Me 321", "Ar 232", "BV 222", "A310 MRTT", "C-160", "A400M"],
        "Airborne Warning and Control System": ["Boeing E-3 Sentry"]
    },
    "Snowdwellers": {
        "Fighter": ["J11", "J8A", "J6B", "J22", "J20", "J26", "J21", "J29", "J32", "J35 'Draken'"],
        "Heavy Fighter": ["Mosquito"],
        "Multirole Fighter/Fighter-Bomber": ["JA37 'Viggen'", "JAS 39 'Gripen'"],
        "Light Bomber/CAS": ["SAAB-105", "A32A", "B17"],
        "Medium Bomber": ["B3C", "B18"],
        "Heavy Bomber": [null],
        "Reconnaissance Aircraft": ["SAAB-105", "B17"],
        "Helicopter": ["HKP3", "HKP2", "HKP9"],
        "Transport Plane/Refuelling Tanker": ["C-390 'Millennium'", "C-130 'Hercules'", "KC-130"],
        "Airborne Warning and Control System": ["Saab 340 AEW&C"]
    },
    "Yankees": {
        "Fighter": ["BF2C", "F2A 'Buffalo'", "F3F", "P-26 'Peashooter'", "P-36 'Hawk'", "F4F 'Wildcat", "F4U 'Corsair'", "F6F 'Wildcat'", "P-39 'Airacobra'", "P-40 'Warhawk'", "P-51 'Mustang'", "F8F 'Bearcat'", "P-47 'Thunderbolt'", "P-63 'Kingcobra'", "F2G 'Super Corsair'", "F-80 'Shooting Star", "F-86 'Sabre'", "F-89 'Scorpion'", "F2H 'Phantom'", "F9F 'Panther'", "F-100 'Super Sabre'", "F-104 'Starfighter'", "F-11 'Tiger'", "F3H 'Demon'", "F4D 'Skyray'", "F8U 'Crusader'", "F-106 'Delta Dart'", "F-5 'Freedom Fighter'"],
        "Heavy Fighter": ["P-38 'Lightning'", "F-82 'Twin Mustang'", "F7F 'Tigercat'", "F-4 'Phantom II", "F-14 'Tomcat'", "F-15C 'Eagle'", "F-22 'Raptor'"],
        "Multirole Fighter/Fighter-Bomber": ["F-16C 'Fighting Falcon'", "F-15E 'Strike Eagle'", "F/A-18C/D 'Hornet'", "F/A-18E/F 'Super Hornet'", "F-35 'Lightning II'", "F-105 'Thunderchief'", "F-111 'Aardvark'"],
        "Light Bomber/CAS": ["A-36 'Apache'", "A-26 'Invader'", "AM-1 'Mauler'", "A-1 'Skyraider'", "A-10 'Thunderbolt II'", "A-4 'Skyhawk'", "F-117 'Nighthawk'", "A-6 'Intruder'", "A-7 'Corsair II'", "SB2U 'Vindicator'", "SBD 'Dauntless'", "TBD 'Devastator'", "TBF/TBM 'Avenger'", "SB2C 'Helldiver'"],
        "Medium Bomber": ["A-20 'Havoc'", "B-25 'Mitchell", "B-10", "B-18", "PBM-1 'Mariner'", "PBY-5 'Catalina'", "B-34 'Lexington'", "PV-2 'Harpoon'", "B-57 'Canberra'"],
        "Heavy Bomber": ["B-17 'Flying Fortress'", "PB4Y 'Liberator'", "B-24 'Liberator'", "B-29 'Superfortress'", "B-36 'Peacemaker'", "B-52 'Stratofortress'", "B-1B 'Lancer'", "B-2 'Spirit'"],
        "Reconnaissance Aircraft": ["SC-1 'Seahawk'", "SR-71 'Blackbird'", "U-2 'Dragon Lady'", "OS2U-1 'Kingfisher'", "PBY-5 'Catalina'"],
        "Helicopter": ["AH-1 'Cobra'", "UH-1 'Iroqois'", "UH-60 'Black Hawk'", "AH-64 'Apache'", "CH-47 'Chinook'", "RAH-66 'Comanche'", "AH-6 'Little Bird'"],
        "Transport Plane/Refuelling Tanker": ["C-17 'Globemaster III'", "C-130 'Hercules'", "C-5 'Galaxy'", "VC-25 (Air Force One)", "KC-46 'Pegasus'", "KC-135 'Stratotanker'"],
        "Airborne Warning and Control System": ["E-3 'Sentry'", "E-2 'Hawkeye'"]
    },
    "Killswitch": {
        "Fighter": ["Sakeen", "Sa'ar", "Sambad", "Kfir C.7", "Shahak"],
        "Heavy Fighter": ["Kurnass 2000", "Baz", ],
        "Multirole Fighter/Fighter-Bomber": ["Netz", "F-15I Ra'am", "F-35I"],
        "Light Bomber/CAS": ["A-4E 'Skyhawk'", "Ayit"],
        "Medium Bomber": ["Vautour IIA"],
        "Heavy Bomber": ["B-17 'Flying Fortress'"],
        "Reconnaissance Aircraft": [null],
        "Helicopter": ["Tzefa", "Peten", "Saraph", "Lahatut"],
        "Transport Plane/Refuelling Tanker": ["C-1030J 'Super Hercules'"],
        "Airborne Warning and Control System": ["Gulfstream G550CAEW"]
    },
    "Chronos": {
        "Fighter": ["J-2", "J-5", "J-7II", "J-6", "J-8B"],
        "Heavy Fighter": ["J-11"],
        "Multirole Fighter/Fighter-Bomber": ["J-10", "J-20", "J-35", "JH-7", ],
        "Light Bomber/CAS": ["Q-5"],
        "Medium Bomber": ["Qing-6", "H-5"],
        "Heavy Bomber": ["H-6"],
        "Reconnaissance Aircraft": ["JZ-8"],
        "Helicopter": ["Z-11", "Z-9", "Z-10", "Z-19"],
        "Transport Plane/Refuelling Tanker": ["Y-20"],
        "Airborne Warning and Control System": ["KJ-2000", "KJ-200", "KJ-500"]
    }
}
export {roles, races, regions, roleSkills, roleWeapon, ranks, guilds, titles, tankVariants, aircraftVariants}